export const NEW_GAME = 'NEW_GAME';
export const REVEAL_TILE = 'REVEAL_TILE';
export const FETCH_NEW_GAME = 'FETCH_NEW_GAME';
export const LOAD_GAME_DATA = 'LOAD_GAME_DATA';
export const SET_GAME_BUTTON_STATUS = 'SET_GAME_BUTTON_STATUS';

export const INCREMENT_GAME_CLOCK = 'INCREMENT_GAME_CLOCK';
export const STOP_GAME_CLOCK = 'STOP_GAME_CLOCK';
export const START_GAME_CLOCK = 'START_GAME_CLOCK';
export const RESET_GAME_CLOCK = 'RESET_GAME_CLOCK';

export const FLAG_TILE = 'FLAG_TILE';
export const REMOVE_FLAG = 'REMOVE_FLAG';